-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.encontrista_inscricao (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  nome_completo_esposo text,
  data_nascimento_esposo date,
  profissao_esposo text,
  como_chamar_esposo text,
  igreja_esposo text,
  local_trabalho_esposo text,
  celular_esposo text,
  instagram_esposo text,
  restricoes_alimentares_esposo text,
  medicamentos_alergias_esposo text,
  religiao_esposo text,
  escolaridade_esposo text,
  nome_completo_esposa text,
  data_nascimento_esposa date,
  profissao_esposa text,
  como_chamar_esposa text,
  igreja_esposa text,
  local_trabalho_esposa text,
  celular_esposa text,
  instagram_esposa text,
  restricoes_alimentares_esposa text,
  medicamentos_alergias_esposa text,
  religiao_esposa text,
  escolaridade_esposa text,
  endereco text,
  numero text,
  complemento text,
  bairro text,
  cidade text,
  uf text,
  cep text,
  data_casamento date,
  telefone_principal text,
  email text,
  possui_filhos boolean,
  quantidade_filhos integer,
  grau_parentesco_outro text,
  nome_responsavel_filhos text,
  endereco_responsavel text,
  numero_responsavel text,
  complemento_responsavel text,
  bairro_responsavel text,
  cidade_responsavel text,
  telefone_responsavel text,
  casal_que_convidou text,
  telefone_casal_que_convidou text,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT encontrista_inscricao_pkey PRIMARY KEY (id)
);
CREATE TABLE public.equipes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  nome text NOT NULL UNIQUE,
  descricao text,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT equipes_pkey PRIMARY KEY (id)
);
CREATE TABLE public.equipes_evento (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  equipe_id uuid NOT NULL,
  evento_id uuid NOT NULL,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT equipes_evento_pkey PRIMARY KEY (id),
  CONSTRAINT equipes_evento_equipe_id_fkey FOREIGN KEY (equipe_id) REFERENCES public.equipes(id),
  CONSTRAINT equipes_evento_evento_id_fkey FOREIGN KEY (evento_id) REFERENCES public.eventos(id)
);
CREATE TABLE public.eventos (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  nome text NOT NULL UNIQUE,
  descricao text,
  local text NOT NULL,
  start_date date NOT NULL,
  end_date date,
  capacity integer,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  valor_encontreiro numeric NOT NULL DEFAULT 80,
  valor_encontrista numeric NOT NULL DEFAULT 120,
  CONSTRAINT eventos_pkey PRIMARY KEY (id)
);
CREATE TABLE public.inscricoes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  evento_id uuid NOT NULL,
  pessoa_id uuid NOT NULL,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'confirmed'::text, 'cancelled'::text])),
  paid_by_pessoa_id uuid,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  tipo text DEFAULT 'encontrista'::text CHECK (tipo = ANY (ARRAY['encontrista'::text, 'encontreiro'::text])),
  valor numeric,
  CONSTRAINT inscricoes_pkey PRIMARY KEY (id),
  CONSTRAINT fk_inscricoes_evento FOREIGN KEY (evento_id) REFERENCES public.eventos(id),
  CONSTRAINT fk_inscricoes_pessoa FOREIGN KEY (pessoa_id) REFERENCES public.pessoas(id),
  CONSTRAINT fk_inscricoes_paid_by FOREIGN KEY (paid_by_pessoa_id) REFERENCES public.pessoas(id)
);
CREATE TABLE public.momentos_do_evento (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  evento_id uuid NOT NULL,
  equipe_id uuid,
  titulo text NOT NULL,
  descricao text,
  start_time timestamp without time zone,
  end_time timestamp without time zone,
  ordem integer,
  previous_step_id uuid,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT momentos_do_evento_pkey PRIMARY KEY (id),
  CONSTRAINT fk_momentos_evento FOREIGN KEY (evento_id) REFERENCES public.eventos(id),
  CONSTRAINT fk_momentos_equipe FOREIGN KEY (equipe_id) REFERENCES public.equipes(id),
  CONSTRAINT fk_momentos_previous FOREIGN KEY (previous_step_id) REFERENCES public.momentos_do_evento(id)
);
CREATE TABLE public.pagamentos_encontreiro_evento (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  pessoa_id uuid NOT NULL,
  evento_id uuid NOT NULL,
  pagou boolean DEFAULT false,
  data_pagamento timestamp without time zone,
  valor numeric,
  metodo text,
  teamrole_id uuid,
  mp_payment_id text,
  qr_code_base64 text,
  qr_code text,
  CONSTRAINT pagamentos_encontreiro_evento_pkey PRIMARY KEY (id),
  CONSTRAINT pagamentos_encontreiro_evento_pessoa_id_fkey FOREIGN KEY (pessoa_id) REFERENCES public.pessoas(id),
  CONSTRAINT pagamentos_encontreiro_evento_evento_id_fkey FOREIGN KEY (evento_id) REFERENCES public.eventos(id),
  CONSTRAINT pagamentos_encontreiro_evento_teamrole_id_fkey FOREIGN KEY (teamrole_id) REFERENCES public.teamrole(id)
);
CREATE TABLE public.pagamentos_inscricao (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  inscricao_id uuid NOT NULL,
  gateway text NOT NULL DEFAULT 'MERCADO_PAGO'::text,
  mp_payment_id text,
  mp_preference_id text,
  mp_status text,
  mp_status_detail text,
  metodo text NOT NULL,
  valor numeric NOT NULL,
  moeda character NOT NULL DEFAULT 'BRL'::bpchar,
  raw_payload jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT pagamentos_inscricao_pkey PRIMARY KEY (id),
  CONSTRAINT pagamentos_inscricao_inscricao_id_fkey FOREIGN KEY (inscricao_id) REFERENCES public.inscricoes(id)
);
CREATE TABLE public.pessoas (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  nome text NOT NULL,
  email text,
  telefone text,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  password_hash text,
  role text DEFAULT 'user'::text,
  CONSTRAINT pessoas_pkey PRIMARY KEY (id)
);
CREATE TABLE public.teamrole (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  pessoa_id uuid NOT NULL,
  equipe_id uuid NOT NULL,
  is_leader boolean DEFAULT false,
  created_at timestamp without time zone DEFAULT now(),
  evento_id uuid,
  pagou boolean DEFAULT false,
  CONSTRAINT teamrole_pkey PRIMARY KEY (id),
  CONSTRAINT fk_teamrole_equipe FOREIGN KEY (equipe_id) REFERENCES public.equipes(id),
  CONSTRAINT fk_teamrole_pessoa FOREIGN KEY (pessoa_id) REFERENCES public.pessoas(id),
  CONSTRAINT teamrole_evento_id_fkey FOREIGN KEY (evento_id) REFERENCES public.eventos(id)
);