
BEGIN
  -- Ordem correta devido às FKs
  TRUNCATE TABLE cadastro RESTART IDENTITY CASCADE;
  TRUNCATE TABLE encontrista_inscriao RESTART IDENTITY CASCADE;
  TRUNCATE TABLE equipes RESTART IDENTITY CASCADE;
  TRUNCATE TABLE equipes_evento RESTART IDENTITY CASCADE;
  TRUNCATE TABLE eventos RESTART IDENTITY CASCADE;
  TRUNCATE TABLE inscricoes RESTART IDENTITY CASCADE;
  TRUNCATE TABLE momentos_do_evento RESTART IDENTITY CASCADE;
  TRUNCATE TABLE pagamentos_encontreiro_evento RESTART IDENTITY CASCADE;
  TRUNCATE TABLE pessoas RESTART IDENTITY CASCADE;
  TRUNCATE TABLE teamrole RESTART IDENTITY CASCADE;
END;




BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
