 CREATE UNIQUE INDEX cadastro_pkey ON public.cadastro USING btree (id);                                           
 CREATE UNIQUE INDEX encontrista_inscricao_pkey ON public.encontrista_inscricao USING btree (id);                 
 CREATE UNIQUE INDEX equipes_nome_key ON public.equipes USING btree (nome);                                       
 CREATE UNIQUE INDEX equipes_pkey ON public.equipes USING btree (id);                                             
 CREATE UNIQUE INDEX equipes_evento_pkey ON public.equipes_evento USING btree (id);                               
 CREATE UNIQUE INDEX unique_equipe_evento ON public.equipes_evento USING btree (equipe_id, evento_id);            
 CREATE UNIQUE INDEX eventos_nome_key ON public.eventos USING btree (nome);                                       
 CREATE UNIQUE INDEX eventos_pkey ON public.eventos USING btree (id);                                             
 CREATE INDEX idx_inscricoes_evento ON public.inscricoes USING btree (evento_id);                                 
 CREATE INDEX idx_inscricoes_pessoa_evento ON public.inscricoes USING btree (pessoa_id, evento_id);               
 CREATE INDEX idx_inscricoes_status ON public.inscricoes USING btree (status);                                    
 CREATE UNIQUE INDEX inscricoes_pkey ON public.inscricoes USING btree (id);                                       
 CREATE UNIQUE INDEX "inscrições_pkey" ON public.inscricoes USING btree (id);                                     
 CREATE UNIQUE INDEX unique_evento_pessoa ON public.inscricoes USING btree (evento_id, pessoa_id);                
 CREATE UNIQUE INDEX unique_pessoa_evento ON public.inscricoes USING btree (pessoa_id, evento_id);                
 CREATE INDEX idx_momentos_evento ON public.momentos_do_evento USING btree (evento_id);                           
 CREATE UNIQUE INDEX momentos_do_evento_pkey ON public.momentos_do_evento USING btree (id);                       
 CREATE INDEX idx_pagamentos_mp_payment ON public.pagamentos_encontreiro_evento USING btree (mp_payment_id);      
 CREATE UNIQUE INDEX pagamentos_encontreiro_evento_pkey ON public.pagamentos_encontreiro_evento USING btree (id); 
 CREATE UNIQUE INDEX pagamentos_inscricao_pkey ON public.pagamentos_inscricao USING btree (id);                   
 CREATE UNIQUE INDEX idx_pessoas_email ON public.pessoas USING btree (email);                                     
 CREATE UNIQUE INDEX pessoas_pkey ON public.pessoas USING btree (id);                                             
 CREATE INDEX idx_teamrole_equipe ON public.teamrole USING btree (equipe_id);                                     
 CREATE UNIQUE INDEX teamrole_pkey ON public.teamrole USING btree (id);                                           
 CREATE UNIQUE INDEX unique_lider_por_equipe ON public.teamrole USING btree (equipe_id) WHERE (is_leader = true); 